### ISSUE TITLE
BUG - Macos/Ableton - Midi notes are recieved in Ableton, but do not show up in the input channels

### ISSUE THREAD

**Issue by FhinMusic** [josephdadams/midi-relay#41] opened 2023-06-06 15:37 UTC
**Describe the bug**
When using Midi relay as an input in ableton live, the midi indicator does blink and it's possible to assign midi notes and cc to different parameters without a problem. But when it comes to using the midi notes on/off as an input on a midi channel (like an external synth) the notes aren't even detected.

**To Reproduce**
1. Use midi-relay with Ableton 11.2.11 on MacOS Ventura 13.3.1, so with through the IAC driver
2. Use the midi relay midi device as input for a midi track (like a midi keyboard), don't forget to use **All Channels** and press **in**
3. Observe that the midi in indicator in the upper right of Ableton is showing the notes are being received, but the usual midi indicator next to All Channels is not showing anything, and no notes are being played by the instrument

**Expected behavior**
Those midi notes should show up as midi notes in ableton and be played, like it does perfectly (I checked) with any other control surface or midi keyboard (regardless if it's in track, remote, sync mode etc)’

**Screenshots**
Midi IN indicator working : 
<img width="176" alt="Screenshot 2023-06-06 at 17 24 20" src="https://github.com/josephdadams/midi-relay/assets/135699909/4a5dc1f6-8893-4b49-b321-e5abd3ad35cc">

No notes being detected in any channel
<img width="182" alt="image" src="https://github.com/josephdadams/midi-relay/assets/135699909/41011435-8770-4d9e-a0ca-9eb94f7b79ee">

The input notes can still be used as random midi controls tho
<img width="84" alt="image" src="https://github.com/josephdadams/midi-relay/assets/135699909/6950f617-52e8-4181-a2a0-9464c575cf96">

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.3.1
 - Version Midi Relay 3.0.5

**Additional context**
I've seen people having similar problems using other solutions with IAC drivers, something to do with timestamps not being sent with the midi message, or some latency stuff, i'm not sure

**Comment by FhinMusic** [comment] 2023-06-06 15:42
[Here's someone that found a fix for the same problem on another virtual midi program](https://github.com/Boddlnagg/midir/issues/94)

**Comment by FhinMusic** [comment] 2023-06-06 15:59
More info using the integrated MIDI Monitor, it seems that the notes played by Midi Relay are incredibly fast and that could be the problem

Here's what a normal Midi keyboard does when playing a G1 on a midi track on ableton 
<img width="320" alt="image" src="https://github.com/josephdadams/midi-relay/assets/135699909/e00c2287-7c4c-4037-9db6-b794784c0ece">

Here's what this button :
![image](https://github.com/josephdadams/midi-relay/assets/135699909/c585a02e-b882-4d11-8ace-3e3990307094)
Does when clicked the same way on the streamdeck ()
<img width="327" alt="image" src="https://github.com/josephdadams/midi-relay/assets/135699909/5dea8501-540d-4040-b66d-c4e272553754">

Observe that there's a CTL message that's received (no idea what it is) and that everything happens basically at the same ms. Using ch16 is not a mistake, it should still show up in _All Channels_, using a note off on release basically just adds a CTL type on top of the rest, but still doesn't work

Also it's playing G0...? I'm confused but maybe it's just offset in ableton and isn't relevant to the problem

**Comment by josephdadams** [comment] 2023-06-13 13:18
This is an interesting one for sure

**Comment by jsjoen7896** [comment] 2023-08-18 03:15
I just added a feature request relating to this same issue. "All Notes Off" (CTL 123) is being sent for every channel on every "Note On" / "Note Off" message. Not sure if this is something with the jzz.midi node module, or something deeper in the system. Notice in the screenshot, "B0"-"BF" is channel 1-16, and "7B" is "All Notes Off".

![Midi messages](https://github.com/josephdadams/midi-relay/assets/56372743/dc820749-2944-4c4a-befa-4acc61359a1c)

**Comment by josephdadams** [comment] 2023-08-18 03:17
I can confirm that I see it also, but I can also confirm I have no idea why it happens

**Comment by jsjoen7896** [comment] 2023-08-18 04:32
So I think I've found the issue doing some node.js testing. I've successfully opened and transmitted MIDI through a local MIDI port on my computer using the jzz node module. As it turns out, every time you close the midi port with "port.close()", it will actually automatically send the "All Notes Off" message for every channel on that port. Same thing when calling "navigator.close()" (JZZ.Close()) as this closes all the ports anyway. This might be a general MIDI protocol thing, but I'm not sure.

If there was some way to keep the ports you are using open during the process, and maybe have a timeout for when there is long inactivity to close the port, that would probably solve the issue.

![image](https://github.com/josephdadams/midi-relay/assets/56372743/3c81f9e4-6b0d-4cb5-ad5c-252d409a0753)
![image](https://github.com/josephdadams/midi-relay/assets/56372743/2b8e1a4e-c344-4e10-91bc-12e2118ad9eb)

**Comment by josephdadams** [comment] 2023-08-18 04:37
https://github.com/josephdadams/midi-relay/blob/f1ca364ac0ea246e862031a67ecb7bf958bc3b1f/midi.js#L143

**Comment by josephdadams** [comment] 2023-08-18 04:37
Mayhaps it’s this

**Comment by josephdadams** [comment] 2023-08-18 13:05
Pushing midi-relay v3.1.1 with a fix for this

**Closed by josephdadams** 2023-08-18 13:05 UTC
