### ISSUE TITLE
Is the browser-based UI working on macOS?

### ISSUE THREAD

**Issue by Gabriele-LS** [josephdadams/midi-relay#23] opened 2021-04-18 19:02 UTC
Hello, I'm new to midi-relay. I just found out that the settings page (http://localhost:4000/settings) is not working on my MacBook Pro. Is that a known issue?

<img width="1404" alt="Screenshot 2021-04-18 at 20 57 02" src="https://user-images.githubusercontent.com/67373152/115157393-4a278600-a089-11eb-93e7-42ba54c1f72b.png">

**Comment by hussra** [comment] 2021-07-19 14:30
I *suspect* this is a duplicate of #14 which was my report of the settings page not working on Windows. Appeared to be probably to do with how the app was packaged for release.

**Closed** 2022-08-06 13:16 UTC
